// <auto-generated />
using System;
using HotelManagementSystem.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HotelManagementSystem.Migrations
{
    [DbContext(typeof(HotelContext))]
    [Migration("20251126180957_AddDatabasehotel")]
    partial class AddDatabasehotel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HotelManagementSystem.Models.Booking", b =>
                {
                    b.Property<int>("bookingid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("bookingid"));

                    b.Property<DateTime>("ChackInDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ChackOutDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("customerid")
                        .HasColumnType("int");

                    b.Property<int>("roomid")
                        .HasColumnType("int");

                    b.HasKey("bookingid");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("HotelManagementSystem.Models.Customer", b =>
                {
                    b.Property<int>("customerid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("customerid"));

                    b.Property<string>("cemail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("cphone")
                        .HasColumnType("int");

                    b.HasKey("customerid");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("HotelManagementSystem.Models.Rooms", b =>
                {
                    b.Property<int>("roomid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("roomid"));

                    b.Property<int>("roomnumber")
                        .HasColumnType("int");

                    b.Property<double>("roomprice")
                        .HasColumnType("float");

                    b.Property<string>("roomstatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("roomtype")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("roomid");

                    b.ToTable("rooms");
                });
#pragma warning restore 612, 618
        }
    }
}
